[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stack"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
QUEUE_CONNECTION = "sync"

[[services]]
name = "web" 